### ISSUE TITLE
Pretrained models, samples and a question

### ISSUE THREAD

**Issue by Dannynis** [cyhuang-tw/AdaIN-VC#1]
Hey, Ive found your repository very interesting and i would like to try it. are there any sample from your trained model on the VCTK data ? also is it possible to get the model you are using ? 
Also i've noticed that during prepossessing, you are creating evaluation and test sets but don't use then anywhere, is it currently WIP ? 
Thank you very much !

**Comment by cyhuang-tw** [comment]
Hi,

Thanks for liking my repository. I just added the link for the pre-trained model at README (at the "Inference" section). You may use the model to generate some samples.

The dev and test sets are not used in the current code, and I will fix this in the future. However, as I am working on another project, I am not able to tell when it will be done.

**Comment by QuantScientist** [comment]
Hello,
Thank you for the great code. 
I am unable to find the pre-trained models. Can you please share them? 
Thanks.

**Comment by cyhuang-tw** [comment]
Hi,

I am currently training a new model, and it will be released soon.
