### ISSUE TITLE
关于声码器

### ISSUE THREAD

**Issue by chestnutly** [cyhuang-tw/AdaIN-VC#10]
您好，你的模型转换效果十分优秀，但我有一个疑问想请教一下，模型中的vocoder是您自己训练的吗？为何我使用yistLin/universal-vocoder项目中的vocoder模型进行转换得到的语音都是静音呢？是否其中还需要其他转换呢？如能赐教，不胜感激。。

**Comment by cyhuang-tw** [comment]
Hi,

You should use the vocoder provided [here](https://drive.google.com/drive/folders/1MacKgXGA4Ad0O_c6W5MlkZMG0B8IzaM-), not the one in Yist's repository. There are some differences in spectrogram configuration, and I think that's why you got silence with the wrong vocoder.

**Comment by chestnutly** [comment]
好的，十分感谢您的解答
