### ISSUE TITLE
metadata.json

### ISSUE THREAD

**Issue by chandrakanthlns** [cyhuang-tw/AdaIN-VC#12]
Hello,
I found this repo very relevant for voice conversion. I started working on this. Got stuck in preparing the metadata. Json. Can someone please send me sample json file so that I will prepare my accordingly.

**Comment by BabaiLi** [comment]
You can find preprocess method in the repository.
Just run the code:
`python preprocess.py <data_dir> <save_dir> [--segment seg_len]
`
