### ISSUE TITLE
Code question

### ISSUE THREAD

**Issue by predawnang** [cyhuang-tw/AdaIN-VC#13]
Hello, dear Author

May I ask what is the purpose of this line of code in file *mel2wav.py*, line132.
 `mel_tensor = (mel_tensor - self.ref_db + self.dc_db) / self.dc_db`
 And is there a technical name for this operation?

This repository is a good work.
Thanks.

**Comment by cyhuang-tw** [comment]
Hi,
I think this is generally called normalization.
