### ISSUE TITLE
Robotic /Metalic voice ?

### ISSUE THREAD

**Issue by QuantScientist** [cyhuang-tw/AdaIN-VC#2]
Hello,
I noticed that the audio samples you provided sound robotic. What is the reason for this? 
Thanks.

**Comment by cyhuang-tw** [comment]
Hi,

Did you mean the audio samples in the demo page from the paper link?
If so, this is because the authors used Griffin-Lim algorithm to generate waveforms from spectrograms in their original implementation. If we use neural vocoder instead, the audio quality improves.
