### ISSUE TITLE
vocoder

### ISSUE THREAD

**Issue by pavelxx1** [cyhuang-tw/AdaIN-VC#6]
I need to train vocoder on my own dataset(non-English) or can use your pretrained vocoder.pt?
thx

**Comment by cyhuang-tw** [comment]
Hi,

The provided vocoder was trained on English datasets only, so I am not sure how it performs in different languages.
For additional information about cross-lingual performance, please refer to [this paper](https://arxiv.org/pdf/1912.02461.pdf).
